SKILL_KEYWORDS = [
    "python",
    "java",
    "javascript",
    "typescript",
    "sql",
    "fastapi",
    "django",
    "flask",
    "spring",
    "node.js",
    "react",
    "streamlit",
    "postgresql",
    "mysql",
    "sqlite",
    "mongodb",
    "docker",
    "git",
    "github",
    "linux",
    "aws",
    "gcp",
    "azure",
    "rest api",
    "api",
    "machine learning",
    "deep learning",
    "nlp",
    "llm",
    "openai",
    "langchain",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "html",
    "css",
    "pytest",
    "ci/cd",
    "kubernetes",
]